export interface User {
  id: string
  name: string
  email: string
  age: number
  type: string
  lifestyle: string
  income: number
  employment: string
  bancarization: string
  devices: number
  techSavvy: boolean
  urbanZone: boolean
  dependents: number
  activityLevel: string
  dailyConnectionTime: number
  hotspotFrequency: string
  rewardsParticipation: number
  leisureTime: number
  avatar: string
}

export const users: User[] = [
  {
    id: "USR001",
    name: "María González",
    email: "maria.gonzalez@email.com",
    age: 32,
    type: "Premium",
    lifestyle: "Activo",
    income: 28000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 5,
    techSavvy: true,
    urbanZone: true,
    dependents: 2,
    activityLevel: "Alto",
    dailyConnectionTime: 10.5,
    hotspotFrequency: "Cada 30 min",
    rewardsParticipation: 95,
    leisureTime: 2.8,
    avatar: "MG",
  },
  {
    id: "USR002",
    name: "Carlos Ramírez",
    email: "carlos.ramirez@email.com",
    age: 45,
    type: "Estándar",
    lifestyle: "Moderado",
    income: 22000,
    employment: "Formal",
    bancarization: "Medio",
    devices: 3,
    techSavvy: false,
    urbanZone: true,
    dependents: 3,
    activityLevel: "Medio",
    dailyConnectionTime: 7.2,
    hotspotFrequency: "Cada 60 min",
    rewardsParticipation: 68,
    leisureTime: 1.5,
    avatar: "CR",
  },
  {
    id: "USR003",
    name: "Ana Martínez",
    email: "ana.martinez@email.com",
    age: 28,
    type: "Premium",
    lifestyle: "Muy Activo",
    income: 35000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 6,
    techSavvy: true,
    urbanZone: true,
    dependents: 0,
    activityLevel: "Muy Alto",
    dailyConnectionTime: 12.3,
    hotspotFrequency: "Cada 20 min",
    rewardsParticipation: 98,
    leisureTime: 3.5,
    avatar: "AM",
  },
  {
    id: "USR004",
    name: "Roberto Silva",
    email: "roberto.silva@email.com",
    age: 52,
    type: "Básico",
    lifestyle: "Sedentario",
    income: 18000,
    employment: "Informal",
    bancarization: "Bajo",
    devices: 2,
    techSavvy: false,
    urbanZone: false,
    dependents: 1,
    activityLevel: "Bajo",
    dailyConnectionTime: 5.5,
    hotspotFrequency: "Cada 120 min",
    rewardsParticipation: 42,
    leisureTime: 4.2,
    avatar: "RS",
  },
  {
    id: "USR005",
    name: "Laura Fernández",
    email: "laura.fernandez@email.com",
    age: 36,
    type: "Premium",
    lifestyle: "Activo",
    income: 32000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 5,
    techSavvy: true,
    urbanZone: true,
    dependents: 2,
    activityLevel: "Alto",
    dailyConnectionTime: 9.8,
    hotspotFrequency: "Cada 35 min",
    rewardsParticipation: 88,
    leisureTime: 2.2,
    avatar: "LF",
  },
  {
    id: "USR006",
    name: "Diego Torres",
    email: "diego.torres@email.com",
    age: 24,
    type: "Estándar",
    lifestyle: "Muy Activo",
    income: 20000,
    employment: "Formal",
    bancarization: "Medio",
    devices: 4,
    techSavvy: true,
    urbanZone: true,
    dependents: 0,
    activityLevel: "Muy Alto",
    dailyConnectionTime: 11.5,
    hotspotFrequency: "Cada 25 min",
    rewardsParticipation: 92,
    leisureTime: 4.0,
    avatar: "DT",
  },
  {
    id: "USR007",
    name: "Patricia Morales",
    email: "patricia.morales@email.com",
    age: 41,
    type: "Estándar",
    lifestyle: "Moderado",
    income: 24000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 4,
    techSavvy: true,
    urbanZone: true,
    dependents: 2,
    activityLevel: "Medio",
    dailyConnectionTime: 8.3,
    hotspotFrequency: "Cada 45 min",
    rewardsParticipation: 75,
    leisureTime: 2.0,
    avatar: "PM",
  },
  {
    id: "USR008",
    name: "Javier López",
    email: "javier.lopez@email.com",
    age: 29,
    type: "Premium",
    lifestyle: "Activo",
    income: 30000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 5,
    techSavvy: true,
    urbanZone: true,
    dependents: 1,
    activityLevel: "Alto",
    dailyConnectionTime: 10.2,
    hotspotFrequency: "Cada 30 min",
    rewardsParticipation: 90,
    leisureTime: 2.5,
    avatar: "JL",
  },
  {
    id: "USR009",
    name: "Carmen Ruiz",
    email: "carmen.ruiz@email.com",
    age: 48,
    type: "Básico",
    lifestyle: "Moderado",
    income: 19000,
    employment: "Informal",
    bancarization: "Medio",
    devices: 3,
    techSavvy: false,
    urbanZone: true,
    dependents: 3,
    activityLevel: "Medio",
    dailyConnectionTime: 6.8,
    hotspotFrequency: "Cada 90 min",
    rewardsParticipation: 55,
    leisureTime: 1.8,
    avatar: "CR",
  },
  {
    id: "USR010",
    name: "Fernando Castro",
    email: "fernando.castro@email.com",
    age: 35,
    type: "Premium",
    lifestyle: "Muy Activo",
    income: 38000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 7,
    techSavvy: true,
    urbanZone: true,
    dependents: 1,
    activityLevel: "Muy Alto",
    dailyConnectionTime: 13.0,
    hotspotFrequency: "Cada 15 min",
    rewardsParticipation: 100,
    leisureTime: 3.2,
    avatar: "FC",
  },
  {
    id: "USR011",
    name: "Sofía Herrera",
    email: "sofia.herrera@email.com",
    age: 26,
    type: "Estándar",
    lifestyle: "Activo",
    income: 23000,
    employment: "Formal",
    bancarization: "Medio",
    devices: 4,
    techSavvy: true,
    urbanZone: true,
    dependents: 0,
    activityLevel: "Alto",
    dailyConnectionTime: 9.5,
    hotspotFrequency: "Cada 40 min",
    rewardsParticipation: 82,
    leisureTime: 3.0,
    avatar: "SH",
  },
  {
    id: "USR012",
    name: "Miguel Ángel Vargas",
    email: "miguel.vargas@email.com",
    age: 55,
    type: "Básico",
    lifestyle: "Sedentario",
    income: 17000,
    employment: "Informal",
    bancarization: "Bajo",
    devices: 2,
    techSavvy: false,
    urbanZone: false,
    dependents: 2,
    activityLevel: "Bajo",
    dailyConnectionTime: 4.5,
    hotspotFrequency: "Cada 150 min",
    rewardsParticipation: 35,
    leisureTime: 5.0,
    avatar: "MV",
  },
  {
    id: "USR013",
    name: "Gabriela Mendoza",
    email: "gabriela.mendoza@email.com",
    age: 31,
    type: "Premium",
    lifestyle: "Activo",
    income: 29000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 5,
    techSavvy: true,
    urbanZone: true,
    dependents: 1,
    activityLevel: "Alto",
    dailyConnectionTime: 10.0,
    hotspotFrequency: "Cada 35 min",
    rewardsParticipation: 87,
    leisureTime: 2.3,
    avatar: "GM",
  },
  {
    id: "USR014",
    name: "Ricardo Ortiz",
    email: "ricardo.ortiz@email.com",
    age: 39,
    type: "Estándar",
    lifestyle: "Moderado",
    income: 25000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 4,
    techSavvy: true,
    urbanZone: true,
    dependents: 2,
    activityLevel: "Medio",
    dailyConnectionTime: 8.0,
    hotspotFrequency: "Cada 50 min",
    rewardsParticipation: 72,
    leisureTime: 2.1,
    avatar: "RO",
  },
  {
    id: "USR015",
    name: "Valentina Rojas",
    email: "valentina.rojas@email.com",
    age: 27,
    type: "Premium",
    lifestyle: "Muy Activo",
    income: 33000,
    employment: "Formal",
    bancarization: "Alto",
    devices: 6,
    techSavvy: true,
    urbanZone: true,
    dependents: 0,
    activityLevel: "Muy Alto",
    dailyConnectionTime: 11.8,
    hotspotFrequency: "Cada 22 min",
    rewardsParticipation: 96,
    leisureTime: 3.8,
    avatar: "VR",
  },
]
